"use client";
import { useState, useEffect } from "react";
import { useToast } from "@/components/toast";
import { Badge, Card, Empty, ErrorBox, Field, Markdown, Modal, PageHeader, Spinner, Source, useConfirm } from "@/components/ui";
import { api, useApi } from "@/lib/client";
import { useShell } from "@/components/shell/Shell";

const TOPICS = [["technical", "Technical analysis"], ["fundamental", "Fundamental analysis"], ["macro", "Macro"], ["structure", "Market structure"], ["risk", "Risk management"], ["psychology", "Psychology"], ["portfolio", "Portfolio management"], ["strategies", "Strategies"]] as const;
interface Lesson { id: string; topic: string; title: string; content: string; quiz: { q: string; options: string[]; answer: number; explanation?: string }[]; source: string; progress: { completedAt: string | null; bestScore: number | null; attempts: number; notes: string | null } | null }

/** Trading Academy (spec §16): lessons, notes, quizzes, progress. Lessons are authored by the user or generated by the AI (labelled). */
export default function AcademyPage() {
  const { aiConfigured } = useShell();
  const toast = useToast();
  const lessons = useApi<Lesson[]>("/api/academy/lessons");
  const { confirm, dialog: confirmDialog } = useConfirm();
  const [open, setOpen] = useState<Lesson | null>(null);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [result, setResult] = useState<number | null>(null);
  const [modal, setModal] = useState(false);
  const [form, setForm] = useState({ topic: "technical", title: "", content: "", quiz: "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const save = async (e: React.FormEvent) => {
    e.preventDefault(); setError("");
    try {
      const quiz = form.quiz.trim() ? JSON.parse(form.quiz) : [];
      await api("/api/academy/lessons", { method: "POST", json: { ...form, quiz, source: "user" } });
      setModal(false); setForm({ topic: "technical", title: "", content: "", quiz: "" }); lessons.refresh();
    } catch (err) { setError((err as Error).message); }
  };
  const generate = async (topic: string) => {
    setBusy(true);
    try {
      const r = await api<{ text: string }>("/api/ai/chat", { method: "POST", json: { text: `Create ONE Trading Academy lesson on the topic "${topic}" for me. Return ONLY a JSON object {"title": string, "content": markdown string (600-900 words, practical, with examples, no guaranteed-return claims), "quiz": [{"q": string, "options": [4 strings], "answer": index, "explanation": string}] (5 questions)}. Do not call tools.` } });
      const json = JSON.parse(r.text.replace(/```json|```/g, "").trim());
      await api("/api/academy/lessons", { method: "POST", json: { topic, title: json.title, content: json.content, quiz: json.quiz, source: "ai" } });
      toast.success("Lesson generated", topic); lessons.refresh();
    } catch (e) { toast.error("Generation failed", (e as Error).message); } finally { setBusy(false); }
  };
  // Opened straight from a search result: select the lesson in the URL once the list has arrived.
  useEffect(() => {
    if (!lessons.data) return;
    const id = new URLSearchParams(window.location.search).get("lesson");
    if (!id) return;
    const found = lessons.data.find((l) => l.id === id);
    if (found) setOpen(found);
  }, [lessons.data]);

  const submitQuiz = async () => {
    if (!open) return;
    const correct = open.quiz.filter((q, i) => answers[i] === q.answer).length;
    const score = Math.round((correct / open.quiz.length) * 100);
    setResult(score);
    await api(`/api/academy/lessons/${open.id}/quiz`, { method: "POST", json: { score } });
    toast[score >= 70 ? "success" : "info"](score >= 70 ? `Passed · ${score}%` : `Score ${score}% — review and retry`); lessons.refresh();
  };
  return (
    <div className="space-y-4">
      <PageHeader back={{ href: "/trading", label: "Trading" }} title="Trading Academy" subtitle="Lessons, notes, quizzes and revision. The AI can teach and test you." action={<button className="btn-primary btn-sm" onClick={() => setModal(true)}>+ Lesson</button>} />
      {lessons.error && <ErrorBox error={lessons.error} retry={lessons.reload} />}
      {lessons.loading && !lessons.data && <Spinner />}
      {lessons.data && (
        <div className="grid gap-3 md:grid-cols-2">
          {TOPICS.map(([id, name]) => { const ls = lessons.data!.filter((l) => l.topic === id); const done = ls.filter((l) => l.progress?.completedAt).length; return (
            <Card key={id} title={name} action={<div className="flex items-center gap-2 text-xs muted">{done}/{ls.length}{aiConfigured && <button className="btn-ghost btn-sm" disabled={busy} onClick={() => generate(id)}>AI lesson</button>}</div>}>
              {ls.length === 0 ? <p className="text-sm muted">No lessons in this topic yet.</p> : <ul className="divide-y divide-border text-sm">{ls.map((l) => <li key={l.id} className="flex items-center gap-2 py-1.5"><button className="flex-1 text-left hover:underline" onClick={() => { setOpen(l); setAnswers({}); setResult(null); }}>{l.title}</button><Source source={l.source} />{l.progress?.bestScore != null && <Badge tone={l.progress.completedAt ? "positive" : "warning"}>{l.progress.bestScore}%</Badge>}</li>)}</ul>}
            </Card>); })}
        </div>
      )}
      {lessons.data?.length === 0 && <Empty>Write your first lesson or let the AI generate one per topic. AI lessons are labelled and are educational, never financial advice.</Empty>}
      <Modal open={!!open} onClose={() => setOpen(null)} title={open?.title ?? ""} wide>
        {open && <div className="space-y-4">
          <Markdown text={open.content} />
          {open.quiz.length > 0 && <div className="card p-3"><p className="mb-2 font-semibold">Quiz</p>{open.quiz.map((q, i) => <div key={i} className="mb-3"><p className="text-sm font-medium">{i + 1}. {q.q}</p><div className="mt-1 grid gap-1">{q.options.map((o, k) => <button key={k} className={"rounded-lg border px-2 py-1 text-left text-sm " + (answers[i] === k ? "border-accent bg-accent text-accent-fg" : "border-border") + (result != null && k === q.answer ? " !border-positive" : "")} onClick={() => result == null && setAnswers({ ...answers, [i]: k })}>{o}</button>)}</div>{result != null && q.explanation && <p className="mt-1 text-xs muted">{q.explanation}</p>}</div>)}{result == null ? <button className="btn-primary btn-sm" disabled={Object.keys(answers).length < open.quiz.length} onClick={submitQuiz}>Submit</button> : <p className="text-sm font-semibold">Score: {result}% {result >= 70 ? "· passed" : "· review and retry"}</p>}</div>}
          <NotesEditor lesson={open} onSaved={lessons.refresh} />
          <button className="btn-ghost btn-sm text-negative" onClick={() => confirm(async () => { await api(`/api/academy/lessons/${open.id}`, { method: "DELETE" }); setOpen(null); lessons.refresh(); toast.success("Lesson deleted", open.title); }, { title: "Delete this lesson?", description: open.title })}>Delete lesson</button>
        </div>}
      </Modal>
      <Modal open={modal} onClose={() => setModal(false)} title="New lesson" wide>
        <form onSubmit={save} className="space-y-3">
          <div className="grid grid-cols-2 gap-2"><Field label="Topic"><select className="field" value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })}>{TOPICS.map(([id, n]) => <option key={id} value={id}>{n}</option>)}</select></Field><Field label="Title"><input className="field" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field></div>
          <Field label="Content (markdown)"><textarea className="field" rows={10} required value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} /></Field>
          <Field label="Quiz JSON (optional)" hint='[{"q":"…","options":["a","b"],"answer":0,"explanation":"…"}]'><textarea className="field" rows={3} value={form.quiz} onChange={(e) => setForm({ ...form, quiz: e.target.value })} /></Field>
          {error && <p className="text-sm text-negative">{error}</p>}
          <div className="flex justify-end"><button className="btn-primary">Save</button></div>
        </form>
      </Modal>
      {confirmDialog}
    </div>
  );
}
function NotesEditor({ lesson, onSaved }: { lesson: Lesson; onSaved: () => void }) {
  const [notes, setNotes] = useState(lesson.progress?.notes ?? "");
  const [saved, setSaved] = useState(false);
  return <div><p className="mb-1 text-sm font-semibold">My notes</p><textarea className="field" rows={3} value={notes} onChange={(e) => { setNotes(e.target.value); setSaved(false); }} /><button className="btn-ghost btn-sm mt-1" onClick={async () => { await api(`/api/academy/lessons/${lesson.id}/notes`, { method: "PUT", json: { notes } }); setSaved(true); onSaved(); }}>{saved ? "Saved" : "Save notes"}</button></div>;
}
