/** Client-side types for API payloads (kept small and structural on purpose). */
export interface Task { id: string; title: string; description: string | null; status: "todo" | "in_progress" | "done" | "cancelled"; priority: "low" | "medium" | "high" | "urgent"; category: string | null; dueDate: string | null; dueTime: string | null; projectId: string | null; goalId: string | null; recurrence: string | null; estimatedMinutes: number | null; completedAt: string | null; source: string }
export interface EventItem { id: string; title: string; description: string | null; kind: string; startAt: string; endAt: string; allDay: boolean; location: string | null; taskId: string | null; projectId: string | null; goalId: string | null; source: string }
export interface Goal { id: string; name: string; description: string | null; category: string; status: string; priority: string; deadline: string | null; progress: number; metricName: string | null; metricUnit: string | null; metricTarget: number | null; metricCurrent: number | null; metricSource: string | null; metricKind: string | null; metricRef: string | null; metricPeriod: string | null }
export interface PlanItem { id: string; kind: "task" | "event" | "note"; status: "proposed" | "accepted" | "rejected" | "skipped"; title: string; notes: string | null; date: string | null; startAt: string | null; endAt: string | null; allDay: boolean; estimatedMinutes: number | null; eventKind: string | null; priority: string | null; projectId: string | null; goalId: string | null; createdTaskId: string | null; createdEventId: string | null }
export interface Plan { id: string; horizon: "day" | "week"; periodKey: string; status: "draft" | "accepted" | "partially_accepted" | "rejected" | "superseded"; title: string | null; content: string; acceptedAt: string | null; rejectedAt: string | null; createdAt: string; items: PlanItem[] }
export interface PlanAcceptResult { itemId: string; title: string; kind: string; status: "created" | "already_created" | "skipped" | "failed"; taskId?: string; eventId?: string; error?: string }
export interface Project { id: string; name: string; description: string | null; kind: string; status: string; priority: string; deadline: string | null; notes: string | null; progress: number; openTasks: number; doneTasks: number; computedProgress: number }
export interface Transaction { id: string; type: "expense" | "income" | "transfer"; amount: number; currency: string; date: string; description: string; merchant: string | null; accountId: string | null; toAccountId: string | null; categoryId: string | null; categoryName?: string | null; accountName?: string | null; source: string }
export interface DashboardData {
  today: string; widgets: string[]; unreadNotifications: number;
  tasks: { today: Task[]; overdue: Task[]; counts: { today: number; overdue: number; open: number } };
  events: EventItem[];
  training: { workout: { dayIndex: number; day: { name: string; isRest: boolean; notes: string | null; exercises: unknown[] } | null; session: { id: string; finishedAt: string | null } | null } | null; recent: { id: string; date: string; dayName: string | null; sets: number; volume: number; status: "started" | "in_progress" | "completed" | "empty"; isWorkout: boolean }[]; week: { from: string; to: string; completed: number; sessions: number; emptySessions: number; plannedDays: number | null; plannedSoFar: number | null } | null };
  finance: { income: number; expenses: number; net: number; savingsRate: number | null; byCategory: { name: string; total: number }[]; budgets: unknown[]; financeBalance: number; accounts: unknown[]; recent: Transaction[]; savings: { id: string; name: string; currentAmount: number; targetAmount: number }[] } | null;
  goals: Goal[]; projects: Project[];
  plan: { day: { id: string; periodKey: string; status: string; title: string | null; items: { id: string; kind: string; status: string; title: string; date: string | null; startAt: string | null; materialised: boolean }[]; pendingItems: number } | null; week: { id: string; status: string; pendingItems: number } | null; draftsAwaitingAnswer: number } | null;
  investing: { totalValue: number; totalCost: number; unrealized: number; cash: number; positions: { asset: { id: string; symbol: string }; value: number | null }[]; unpriced: string[] } | null;
  trading: { openTrades: { id: string; symbol: string; direction: string; mode: string }[]; watchlists: { items: { symbol: string }[] }[]; economicEvents: { id: string; title: string }[] };
  news: { id: string; headline: string; url: string; source: string }[];
  studies: { totalMinutes: number; bySubject: { name: string; minutes: number; weeklyGoalMinutes: number | null }[]; exams: { title: string; date: string }[]; german: { streak: number; xp: number; unitsPassed: number } | null } | null;
  nutrition: { totals: { calories: number; protein: number }; goals: { calories: number; protein: number }; meals: number; estimatedItems: number } | null;
}
