import { z } from "zod";
import { defineTool } from "../registry";
import * as g from "@/server/services/goals";

const LINKED = "Linked goals: set metricSource + metricKind + metricPeriod and the goal tracks real data automatically (no manual updates). Allowed: tasks/completed_tasks (week|month|total, metricRef = project id, otherwise the tasks linked to this goal), training/completed_workouts or training/volume_kg (week|month|total), study/minutes (week|month|total, metricRef = subject id or slug), german/minutes (week|month|total) or german/units_passed (total), finance/net_savings or finance/income (week|month|total). A linked goal needs a positive metricTarget and its progress can never be set by hand.";

defineTool({ name: "get_goals", module: "goals", risk: "read", description: "List goals (default active) with progress and deadlines.", schema: z.object({ status: z.enum(["active", "paused", "completed", "abandoned"]).optional(), id: z.string().uuid().optional() }), run: (i, ctx) => (i.id ? g.getGoal(ctx.user.id, i.id, ctx.user.timezone) : g.listGoals(ctx.user.id, i.status ?? "active", ctx.user.timezone)) });
defineTool({ name: "create_goal", module: "goals", risk: "low", description: `Create a goal; optional metric (name/unit/target) makes progress computable. ${LINKED}`, schema: g.goalCreateSchema.omit({ source: true }), summarize: (i) => `create_goal — ${i.name}`, run: (i, ctx) => g.createGoal(ctx.user.id, { ...i, source: "ai" }, ctx.user.timezone) });
defineTool({ name: "update_goal", module: "goals", risk: "medium", description: `Update a goal (name, deadline, status, metric...). Confirmation required when changing status to abandoned. ${LINKED}`, schema: z.object({ id: z.string().uuid() }).extend(g.goalUpdateSchema.omit({ source: true }).shape), needsConfirmation: (i) => (i.status === "abandoned" ? "Abandon goal" : false), summarize: (i) => `update_goal — ${i.id.slice(0, 8)}`, run: ({ id, ...rest }, ctx) => g.updateGoal(ctx.user.id, id, rest, ctx.user.timezone) });
defineTool({ name: "update_goal_progress", module: "goals", risk: "low", description: "Set progress (0-100) or metricCurrent, or add a delta to the metric. Only for manual goals: a linked goal (metricSource set) is computed from its module and rejects this call — log the activity instead.", schema: z.object({ id: z.string().uuid(), progress: z.number().int().min(0).max(100).optional(), metricCurrent: z.number().optional(), delta: z.number().optional() }), summarize: (i) => `update_goal_progress — ${i.id.slice(0, 8)}`, run: ({ id, ...rest }, ctx) => g.updateGoalProgress(ctx.user.id, id, rest, ctx.user.timezone) });
defineTool({ name: "add_milestone", module: "goals", risk: "low", description: "Add a milestone to a goal.", schema: z.object({ goalId: z.string().uuid(), title: z.string(), dueDate: z.string().optional() }), summarize: (i) => `add_milestone — ${i.title}`, run: (i, ctx) => g.addMilestone(ctx.user.id, i.goalId, { title: i.title, dueDate: i.dueDate, position: 0 }) });
