import { z } from "zod";
import { defineTool } from "../registry";
import * as g from "@/server/services/goals";

defineTool({ name: "get_goals", module: "goals", risk: "read", description: "List goals (default active) with progress and deadlines.", schema: z.object({ status: z.enum(["active", "paused", "completed", "abandoned"]).optional(), id: z.string().uuid().optional() }), run: (i, ctx) => (i.id ? g.getGoal(ctx.user.id, i.id) : g.listGoals(ctx.user.id, i.status ?? "active")) });
defineTool({ name: "create_goal", module: "goals", risk: "low", description: "Create a goal; optional metric (name/unit/target) makes progress computable.", schema: g.goalCreateSchema.omit({ source: true }), summarize: (i) => `create_goal — ${i.name}`, run: (i, ctx) => g.createGoal(ctx.user.id, { ...i, source: "ai" }) });
defineTool({ name: "update_goal", module: "goals", risk: "medium", description: "Update a goal (name, deadline, status, metric...). Confirmation required when changing status to abandoned.", schema: z.object({ id: z.string().uuid() }).extend(g.goalUpdateSchema.omit({ source: true }).shape), needsConfirmation: (i) => (i.status === "abandoned" ? "Abandon goal" : false), summarize: (i) => `update_goal — ${i.id.slice(0, 8)}`, run: ({ id, ...rest }, ctx) => g.updateGoal(ctx.user.id, id, rest) });
defineTool({ name: "update_goal_progress", module: "goals", risk: "low", description: "Set progress (0-100) or metricCurrent, or add a delta to the metric.", schema: z.object({ id: z.string().uuid(), progress: z.number().int().min(0).max(100).optional(), metricCurrent: z.number().optional(), delta: z.number().optional() }), summarize: (i) => `update_goal_progress — ${i.id.slice(0, 8)}`, run: ({ id, ...rest }, ctx) => g.updateGoalProgress(ctx.user.id, id, rest) });
defineTool({ name: "add_milestone", module: "goals", risk: "low", description: "Add a milestone to a goal.", schema: z.object({ goalId: z.string().uuid(), title: z.string(), dueDate: z.string().optional() }), summarize: (i) => `add_milestone — ${i.title}`, run: (i, ctx) => g.addMilestone(ctx.user.id, i.goalId, { title: i.title, dueDate: i.dueDate, position: 0 }) });
